### ISSUE TITLE
Catching error on susbcribing to a non existing destination?

### ISSUE THREAD

**Issue by aalbericio** [stomp-js/stomp-websocket#48]
Hello,

I'm using the latest version of the library (4.0.8) and I'm trying to find a way to "**catch**" the error when **subscribing to a non existing destination**:

>> client.subscribe('foobar')

Since '**foobar**' does not exist as a real stomp destination on the server, stompjs **unsubscribes from all already subscribed (and working) subscriptions**.

When I try to subscribe to a non existing destination, I'd like stompjs to just throw some kind of catchable error but keep the connection and the working subscriptions alive.

Is this possible? Am I doing something wrong?

Thank you.

**Comment by kum-deepak** [comment]
The STOMP standards specify that on any ERROR, the broker is supposed to send an ERROR frame and close the connection.

So, a complaint broker is likely to follow this and close the connection if there is an error during subscription because destination does not exist. Actual behavior may vary by the specific broker in use.

So, check the log output and see if after attempting to subscribe non existent destination, if it drops the connection and reconnects.

**Comment by aalbericio** [comment]
Sorry Deepak, 

We had a reactive chain defined that effectively closed the connection on error. It's not a StompJS issue.

I close the issue.
